export const FormItems = {
    labelWidth: "125px",
    name: "baseForm",
    data: [{
            label: "数据来源",
            prop: "dataSource",
            type: "input",
            disabled: false,
            placeholder: "",
            size: "mini",
        },
        {
            label: "统一社会信用代码",
            prop: "creditCode",
            type: "input",
            disabled: false,
            size: "mini",
            placeholder: "",
        },
        {
            label: "单位详细名称",
            prop: "companyName",
            type: "input",
            disabled: false,
            placeholder: "",
            size: "mini",
            option: [],
        },
        {
            label: "外呼状态",
            prop: "callStatus",
            type: "select",
            disabled: false,
            placeholder: "",
            size: "mini",
            option: [],
        },
        // {
        //   label: "运行结束时间",
        //   prop: "endTime",
        //   type: "date-picker",
        //   disabled: false,
        //   placeholder: "",
        //   size: "mini",
        // },
        {
            label: "电话核实结果",
            prop: "callResult",
            type: "select",
            disabled: false,
            placeholder: "",
            size: "mini",
            option: [],
        },
        {
            label: "身份核实结果",
            prop: "idResult",
            type: "select",
            disabled: false,
            size: "mini",
            placeholder: "",
            option: [],
        },
        {
            label: "地址核实结果",
            prop: "addressResult",
            type: "select",
            disabled: false,
            size: "mini",
            placeholder: "",
            option: [],
        },
        {
            label: "运行时间",
            prop: "updateTime",
            modelDataStartKey: "startTime",
            modelDataEndKey: "endTime",
            type: "date-picker-double",
            disabled: false,
            placeholder: "",
            size: "mini",
        },
    ],
    rules: {},
};