export const FormItems = {
    labelWidth: "125px",
    name: "baseForm",
    data: [{
            label: "统一社会信用代码",
            prop: "creditCode",
            type: "input",
            disabled: false,
            placeholder: "",
            size: "mini",
            isShowMore: true,
        },
        {
            label: "单位详细名称",
            prop: "companyName",
            type: "input",
            disabled: false,
            placeholder: "",
            size: "mini",
        },
        {
            label: "是否规上",
            prop: "isUp",
            type: "select",
            disabled: false,
            size: "mini",
            placeholder: "",
            option: [{
                    text: "是",
                    value: "0",
                },
                {
                    text: "否",
                    value: "1",
                },
            ],
        },
        {
            label: "企业规模",
            prop: "enterpriseSize",
            type: "select",
            disabled: false,
            placeholder: "",
            size: "mini",
            option: [],
        },
        {
            label: "类型",
            prop: "type",
            type: "select",
            disabled: false,
            placeholder: "",
            size: "mini",
            option: [{
                    text: "法人单位",
                    value: "0",
                },
                {
                    text: "产业活动单位",
                    value: "1",
                },
            ],
        },
        {
            label: "行业代码",
            prop: "industryCode",
            type: "select-tree",
            disabled: false,
            placeholder: "",
            size: "mini",
            option: [],
        },
        {
            label: "标签",
            prop: "manualLabel",
            type: "select-tree",
            disabled: false,
            size: "mini",
            placeholder: "",
            //通过接口查询
            option: [],
        },
        {
            label: "模板查询",
            prop: "template",
            type: "select-edit",
            disabled: false,
            size: "mini",
            placeholder: "",
            option: [],
        },
    ],
    rules: {},
};